### ISSUE TITLE
bcm2837-lpa unable to extract on Windows

### ISSUE THREAD

**Issue by AdnoC** [abt8601/raspi-pacs#1]
I realize this is generated code, so if this issue should be in the SVD2Rust repo I will move it there.

The bcm2837-lpa crate includes an [`aux`](https://github.com/abt8601/raspi-pacs/tree/main/crates/bcm2837-lpa/src/aux) module that causes the crate to be uncompileable on Windows. This is because `aux` is one of the few names that files aren't allowed to be named on Windows.

**Comment by abt8601** [comment]
djmcgill/form#12 is the upstream issue, but there hasn't been much progress on it recently.

I'm following riscv-rust/k210-pac@b044481 and not using `form` to format the source files as a temporary fix.

**Comment by abt8601** [comment]
Fixed in 3c5b4c5 and release v0.2.1.
