### ISSUE TITLE
BCM2711 segfaults trying to read UART

### ISSUE THREAD

**Issue by dhan2325** [abt8601/raspi-pacs#2]
I'm trying to use the BCM2711-lpa crate to read the registers on the UART0 on a Raspberry Pi 4. I'm successfully able to "steal" the peripherals, but when trying to read the registers, I'm getting a segmentation fault. I've double checked that my Bluetooth is disabled and that UART is enabled in my config.txt, is there something else I need to set up before I can my program? Any help is appreciated.

My code:
```
fn main() {
    let uart = unsafe {bcm2711_lpa::Peripherals::steal() }.UART0;
    println!("stole peripherals");
    
    let ifls = uart.ifls();
    println!("got IFLS");
    let imsc = uart.imsc();
    println!("got IMSC");

    let r1 = ifls.read().bits();
    println!("read ifls");
    let r2 = imsc.read().bits();
    println!("read imsc");
    let m1 = r1 & RXIFLSEL;
    let m2 = r2 & RXIM;

    println!("ifls read: {:#34b}, {:#18b}", r1, m1);
    println!("imsc read: {:#34b}, {:#18b}", r2, m2);
   
}
```

output:
```
stole peripherals
got IFLS
got IMSC
Segmentation fault
```

**Comment by abt8601** [comment]
I believe you're running your program on top of an operating system like Linux. In this case, this crate cannot be used. You should look for the interface provided by the operating system or other libraries using it. This crate, and peripheral access crates in general, are meant to be used when developing bare-metal software.
